// Start-time secret refresh. Compose's env_file is read once, at container
// creation, so a token rotated in ~/.cww/env (or a git credential rotated in
// ~/.cww/credentials) never reaches an existing workspace on its own. Before
// starting a stopped workspace, cww stages the current secrets — every
// registered agent's auth env keys found in ~/.cww/env, plus this repo's git
// credential — as a shell-sourceable file, docker-cp's it to
// /home/developer/.cww-env-refresh, and the entrypoint sources it over the
// frozen create-time env on every boot (docker/base/entrypoint.sh). Only
// secrets ride this channel: CWW_BROWSER/CWW_AGENT and friends stay
// create-time decisions.
//
// Every failure here degrades to a warning — a stale token beats a workspace
// that won't start.

import { $ } from "bun";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
// Registry values are only read inside function bodies (same import-cycle
// caution as docker.ts — this module sits in the registry's import graph).
import { allAuthEnvKeys } from "../agents/registry";
import { loadCredentials, matchCredential, type Credential } from "./credentials";
import { parseEnvFile } from "./env";
import { readSession } from "./session";
import { info, warn } from "./ui";

// Where the refresh file lands in the container. The entrypoint and the baked
// .bashrc source it; it is deliberately left in place after sourcing so a
// bare 'docker restart' outside cww still applies the last refreshed values.
export const REFRESH_FILE = "/home/developer/.cww-env-refresh";

// Single-quote a value for POSIX shell sourcing: embedded quotes become
// '\'' — everything else ($, backticks, newlines) is inert inside 'single
// quotes'.
export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

// The sourceable file body: assignments only (no commands), so the
// entrypoint's `set -e` can never trip over it.
export function buildRefreshContent(entries: Record<string, string>): string {
  const lines = Object.entries(entries).map(([key, value]) => `${key}=${shellQuote(value)}`);
  return `# Generated by cww — current secrets, sourced by the entrypoint on every\n# container start (see src/lib/env-refresh.ts). Do not edit.\n${lines.join("\n")}\n`;
}

// The secrets worth refreshing: the agent auth keys present in the global env
// file, plus the repo's git credential when one matches. A key absent from
// ~/.cww/env is simply not written — the container keeps its create-time
// value (no unset).
export function collectRefreshEntries(
  envFileText: string,
  authKeys: string[],
  cred: Credential | null,
): Record<string, string> {
  const env = parseEnvFile(envFileText);
  const out: Record<string, string> = {};
  for (const key of authKeys) {
    if (env[key] !== undefined) out[key] = env[key];
  }
  if (cred) {
    out.CWW_GIT_USER = cred.user;
    out.CWW_GIT_TOKEN = cred.token;
  }
  return out;
}

// Write the per-workspace env file carrying this repo's credential from
// ~/.cww/credentials into the container — the only git credential the
// workspace ever sees. Runs on create AND recreate, so re-running 'cww init'
// then recreating a workspace rotates its token. With no matching entry
// (public repo) a stale file is removed and the clone runs unauthenticated.
export function writeTaskEnv(taskDir: string, repoUrl: string): void {
  const file = path.join(taskDir, "env");
  const cred = matchCredential(loadCredentials(), repoUrl);
  if (!cred) {
    fs.rmSync(file, { force: true });
    info(`No stored credential for ${repoUrl} (public repo?) — pushes will need 'cww init'.`);
    return;
  }
  info(`Using stored git credential for ${cred.url} (user: ${cred.user})`);
  writeGitEnvFile(file, cred);
}

function writeGitEnvFile(file: string, cred: Credential): void {
  fs.writeFileSync(file, `CWW_GIT_USER=${cred.user}\nCWW_GIT_TOKEN=${cred.token}\n`, {
    mode: 0o600,
  });
  fs.chmodSync(file, 0o600); // writeFileSync's mode only applies on create
}

// Stage the current secrets and copy them into the (stopped) container —
// docker cp works regardless of container state. Quietly a no-op when there
// is nothing to refresh or no task dir (the attach/shell pattern-matched
// fallback).
export async function refreshWorkspaceSecrets(
  taskDir: string | null,
  container: string,
): Promise<void> {
  if (!taskDir) return;

  let envText = "";
  try {
    envText = fs.readFileSync(path.join(os.homedir(), ".cww", "env"), "utf8");
  } catch {
    // No global env file — agent keys may still live in the caller's
    // environment, but that channel is create-time only; nothing to refresh.
  }

  // The repo's current credential, from the workspace's recorded clone URL.
  // Pre-feature sessions without repoUrl just skip the git half.
  let cred: Credential | null = null;
  try {
    const repoUrl = readSession(taskDir).repoUrl;
    if (typeof repoUrl === "string" && repoUrl) {
      cred = matchCredential(loadCredentials(), repoUrl);
    }
  } catch {
    // Corrupt session.json: other commands will complain; the refresh just
    // skips the git credential.
  }

  const entries = collectRefreshEntries(envText, allAuthEnvKeys(), cred);
  if (Object.keys(entries).length === 0) return;

  // Keep the compose-side copy in step, so a future recreate (compose reads
  // {taskDir}/env at up time) uses the same credential the refresh delivered.
  if (cred) writeGitEnvFile(path.join(taskDir, "env"), cred);

  // Stage dir is 0700 (mkdtemp default): the file itself is 0644 so the
  // in-container 'developer' user can read it after docker cp (which keeps
  // the source mode but roots the ownership); hardenRefreshFile tightens it
  // once the container runs.
  const stage = fs.mkdtempSync(path.join(os.tmpdir(), "cww-envrefresh-"));
  try {
    const staged = path.join(stage, "env-refresh");
    fs.writeFileSync(staged, buildRefreshContent(entries), { mode: 0o644 });
    const r = await $`docker cp ${staged} ${container}:${REFRESH_FILE}`.quiet().nothrow();
    if (r.exitCode !== 0) {
      warn("Could not refresh credentials into the workspace; it starts with its previous tokens.");
    }
  } finally {
    fs.rmSync(stage, { recursive: true, force: true });
  }
}

// Best-effort post-start hardening of the copied file (docker cp leaves it
// root-owned; the entrypoint runs as 'developer' and cannot chown). Failure
// is ignored: the same secrets are visible in every in-container process env
// anyway.
export async function hardenRefreshFile(container: string): Promise<void> {
  const script = `[ ! -f ${REFRESH_FILE} ] || { chown developer:developer ${REFRESH_FILE} && chmod 600 ${REFRESH_FILE}; }`;
  await $`docker exec -u root ${container} sh -c ${script}`.quiet().nothrow();
}
