// Start-time secret refresh. Compose's env_file is read once, at container
// creation, so a token rotated in ~/.cww/env (or a git credential rotated in
// ~/.cww/credentials) never reaches an existing workspace on its own. Before
// starting a stopped workspace, cww stages the current secrets — the env key
// of the workspace's chosen auth method found in ~/.cww/env, plus this
// repo's git credential — as a shell-sourceable file, docker-cp's it to
// /home/developer/.cww-env-refresh, and the entrypoint sources it over the
// frozen create-time env on every boot (docker/base/entrypoint.sh). Only
// secrets ride this channel: CWW_BROWSER/CWW_AGENT and friends stay
// create-time decisions.
//
// Every failure here degrades to a warning — a stale token beats a workspace
// that won't start.

import { $ } from "bun";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
// Registry values are only read inside function bodies (same import-cycle
// caution as docker.ts — this module sits in the registry's import graph).
import {
  agentAuthEnvKeys,
  agentAuthMethods,
  allAuthEnvKeys,
  CWW_AGENTS,
  type Agent,
} from "../agents/registry";
import { loadCredentials, matchCredential, type Credential } from "./credentials";
import { parseEnvFile } from "./env";
import { readSession, type Session } from "./session";
import { info, warn } from "./ui";

// Where the refresh file lands in the container. The entrypoint and the baked
// .bashrc source it; it is deliberately left in place after sourcing so a
// bare 'docker restart' outside cww still applies the last refreshed values.
export const REFRESH_FILE = "/home/developer/.cww-env-refresh";

// Single-quote a value for POSIX shell sourcing: embedded quotes become
// '\'' — everything else ($, backticks, newlines) is inert inside 'single
// quotes'.
export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

// The sourceable file body: assignments only (no commands), so the
// entrypoint's `set -e` can never trip over it.
export function buildRefreshContent(entries: Record<string, string>): string {
  const lines = Object.entries(entries).map(([key, value]) => `${key}=${shellQuote(value)}`);
  return `# Generated by cww — current secrets, sourced by the entrypoint on every\n# container start (see src/lib/env-refresh.ts). Do not edit.\n${lines.join("\n")}\n`;
}

// The agent env keys a workspace's refresh may carry, from its recorded
// session: the chosen auth method's single key (none for the keyless
// methods). Sessions from before the method was recorded fall back to the
// recorded agent's whole key list, and sessions without a usable agent to
// the all-agents union — both matching what those workspaces were created
// with under the old blanket env_file.
export function sessionAuthKeys(session: Session): string[] {
  const agent = typeof session.agent === "string" ? session.agent : "";
  if (!(CWW_AGENTS as readonly string[]).includes(agent)) return allAuthEnvKeys();
  if (typeof session.auth === "string") {
    const method = agentAuthMethods(agent as Agent).find((m) => m.id === session.auth);
    if (method) return method.envKey ? [method.envKey] : [];
  }
  return agentAuthEnvKeys(agent as Agent);
}

// The secrets worth refreshing: the agent auth keys present in the global env
// file, plus the repo's git credential when one matches. A key absent from
// ~/.cww/env is simply not written — the container keeps its create-time
// value (no unset).
export function collectRefreshEntries(
  envFileText: string,
  authKeys: string[],
  cred: Credential | null,
): Record<string, string> {
  const env = parseEnvFile(envFileText);
  const out: Record<string, string> = {};
  for (const key of authKeys) {
    if (env[key] !== undefined) out[key] = env[key];
  }
  if (cred) {
    out.CWW_GIT_USER = cred.user;
    out.CWW_GIT_TOKEN = cred.token;
  }
  return out;
}

// Write the per-workspace env file carrying this repo's credential from
// ~/.cww/credentials — the only git credential the workspace ever sees — and
// the chosen auth method's key: the only agent credential it sees. Runs on
// create AND recreate, so re-running 'cww init' then recreating a workspace
// rotates its token. With nothing to carry (public repo, keyless method) a
// stale file is removed and the clone runs unauthenticated.
export function writeTaskEnv(
  taskDir: string,
  repoUrl: string,
  agentEntries: Record<string, string> = {},
): void {
  const cred = matchCredential(loadCredentials(), repoUrl);
  if (cred) {
    info(`Using stored git credential for ${cred.url} (user: ${cred.user})`);
  } else {
    info(`No stored credential for ${repoUrl} (public repo?) — pushes will need 'cww init'.`);
  }
  writeTaskEnvEntries(taskDir, {
    ...agentEntries,
    ...(cred ? { CWW_GIT_USER: cred.user, CWW_GIT_TOKEN: cred.token } : {}),
  });
}

function writeTaskEnvEntries(taskDir: string, entries: Record<string, string>): void {
  const file = path.join(taskDir, "env");
  const lines = Object.entries(entries).map(([key, value]) => `${key}=${value}`);
  if (lines.length === 0) {
    fs.rmSync(file, { force: true });
    return;
  }
  fs.writeFileSync(file, `${lines.join("\n")}\n`, { mode: 0o600 });
  fs.chmodSync(file, 0o600); // writeFileSync's mode only applies on create
}

// Stage the current secrets and copy them into the (stopped) container —
// docker cp works regardless of container state. Quietly a no-op when there
// is nothing to refresh or no task dir (the attach/shell pattern-matched
// fallback).
export async function refreshWorkspaceSecrets(
  taskDir: string | null,
  container: string,
): Promise<void> {
  if (!taskDir) return;

  let envText = "";
  try {
    envText = fs.readFileSync(path.join(os.homedir(), ".cww", "env"), "utf8");
  } catch {
    // No global env file — agent keys may still live in the caller's
    // environment, but that channel is create-time only; nothing to refresh.
  }

  // The workspace's session scopes the refresh: its recorded auth method
  // picks the agent key, its recorded clone URL the git credential.
  // A corrupt session.json degrades to the all-keys, no-git behavior; other
  // commands complain about the file itself.
  let session: Session = {};
  try {
    session = readSession(taskDir);
  } catch {
    // fall through with the empty session
  }
  let cred: Credential | null = null;
  if (typeof session.repoUrl === "string" && session.repoUrl) {
    cred = matchCredential(loadCredentials(), session.repoUrl);
  }

  const entries = collectRefreshEntries(envText, sessionAuthKeys(session), cred);
  if (Object.keys(entries).length === 0) return;

  // Keep the compose-side copy in step, so a future recreate (compose reads
  // {taskDir}/env at up time) uses the same credentials the refresh
  // delivered. `entries` is exactly what the task env carries: the agent
  // key(s) plus the git credential.
  writeTaskEnvEntries(taskDir, entries);

  // Stage dir is 0700 (mkdtemp default): the file itself is 0644 so the
  // in-container 'developer' user can read it after docker cp (which keeps
  // the source mode but roots the ownership); hardenRefreshFile tightens it
  // once the container runs.
  const stage = fs.mkdtempSync(path.join(os.tmpdir(), "cww-envrefresh-"));
  try {
    const staged = path.join(stage, "env-refresh");
    fs.writeFileSync(staged, buildRefreshContent(entries), { mode: 0o644 });
    const r = await $`docker cp ${staged} ${container}:${REFRESH_FILE}`.quiet().nothrow();
    if (r.exitCode !== 0) {
      warn("Could not refresh credentials into the workspace; it starts with its previous tokens.");
    }
  } finally {
    fs.rmSync(stage, { recursive: true, force: true });
  }
}

// Best-effort post-start hardening of the copied file (docker cp leaves it
// root-owned; the entrypoint runs as 'developer' and cannot chown). Failure
// is ignored: the same secrets are visible in every in-container process env
// anyway.
export async function hardenRefreshFile(container: string): Promise<void> {
  const script = `[ ! -f ${REFRESH_FILE} ] || { chown developer:developer ${REFRESH_FILE} && chmod 600 ${REFRESH_FILE}; }`;
  await $`docker exec -u root ${container} sh -c ${script}`.quiet().nothrow();
}
