import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { allAuthEnvKeys } from "../src/agents/registry";
import {
  buildRefreshContent,
  collectRefreshEntries,
  sessionAuthKeys,
  shellQuote,
  writeTaskEnv,
} from "../src/lib/env-refresh";

describe("shellQuote", () => {
  test("wraps plain values in single quotes", () => {
    expect(shellQuote("abc123")).toBe("'abc123'");
  });

  test("keeps shell-active characters inert", () => {
    expect(shellQuote("a$b`c")).toBe("'a$b`c'");
    expect(shellQuote("line1\nline2")).toBe("'line1\nline2'");
  });

  test("escapes embedded single quotes", () => {
    expect(shellQuote("it's")).toBe(`'it'\\''s'`);
  });
});

describe("buildRefreshContent", () => {
  test("emits one quoted assignment per entry after the header", () => {
    const content = buildRefreshContent({ A: "1", B: "x y" });
    const lines = content.split("\n");
    expect(lines[0]).toStartWith("# Generated by cww");
    expect(content).toContain("A='1'\n");
    expect(content).toContain("B='x y'\n");
    expect(content).toEndWith("\n");
  });

  test("contains assignments only (no commands), even for hostile values", () => {
    const content = buildRefreshContent({ TOKEN: "x'; rm -rf / #" });
    expect(content).toContain(`TOKEN='x'\\''; rm -rf / #'\n`);
  });
});

describe("collectRefreshEntries", () => {
  const ENV_TEXT = [
    "# agent tokens",
    "CLAUDE_CODE_OAUTH_TOKEN=sk-ant-oat01-abc",
    "MISTRAL_API_KEY='m-key'",
    "CWW_BROWSER=off",
  ].join("\n");

  test("filters the env file down to the given auth keys", () => {
    const entries = collectRefreshEntries(
      ENV_TEXT,
      ["CLAUDE_CODE_OAUTH_TOKEN", "MISTRAL_API_KEY", "ANTHROPIC_API_KEY"],
      null,
    );
    expect(entries).toEqual({
      CLAUDE_CODE_OAUTH_TOKEN: "sk-ant-oat01-abc",
      MISTRAL_API_KEY: "m-key", // quotes stripped by the env parser
    });
  });

  test("never forwards non-auth keys like CWW_BROWSER", () => {
    const entries = collectRefreshEntries(ENV_TEXT, ["CLAUDE_CODE_OAUTH_TOKEN"], null);
    expect(Object.keys(entries)).toEqual(["CLAUDE_CODE_OAUTH_TOKEN"]);
  });

  test("adds the git credential when one matches", () => {
    const entries = collectRefreshEntries("", [], {
      user: "dev",
      token: "pat-123",
      url: "https://forge.example.com/org/repo",
    });
    expect(entries).toEqual({ CWW_GIT_USER: "dev", CWW_GIT_TOKEN: "pat-123" });
  });

  test("empty env file and no credential yields nothing to refresh", () => {
    expect(collectRefreshEntries("", ["CLAUDE_CODE_OAUTH_TOKEN"], null)).toEqual({});
  });
});

describe("sessionAuthKeys", () => {
  test("a recorded method narrows the refresh to its single key", () => {
    expect(sessionAuthKeys({ agent: "claude", auth: "oauth-token" })).toEqual([
      "CLAUDE_CODE_OAUTH_TOKEN",
    ]);
    expect(sessionAuthKeys({ agent: "claude", auth: "api-key" })).toEqual(["ANTHROPIC_API_KEY"]);
  });

  test("a keyless method refreshes no agent secret at all", () => {
    expect(sessionAuthKeys({ agent: "claude", auth: "none" })).toEqual([]);
    expect(sessionAuthKeys({ agent: "vibe", auth: "config-file" })).toEqual([]);
  });

  test("sessions without a recorded method fall back to the agent's key list", () => {
    expect(sessionAuthKeys({ agent: "vibe" })).toEqual(["MISTRAL_API_KEY"]);
    expect(sessionAuthKeys({ agent: "vibe", auth: "no-such-method" })).toEqual(["MISTRAL_API_KEY"]);
  });

  test("sessions without a usable agent fall back to every agent's keys", () => {
    expect(sessionAuthKeys({})).toEqual(allAuthEnvKeys());
    expect(sessionAuthKeys({ agent: "mystery" })).toEqual(allAuthEnvKeys());
  });
});

describe("writeTaskEnv", () => {
  // A URL no stored credential can match (.invalid is reserved), so the test
  // covers the agent-entry half regardless of the machine's ~/.cww files.
  const REPO_URL = "https://cww-test.invalid/org/repo.git";

  function tempTaskDir(): string {
    return fs.mkdtempSync(path.join(os.tmpdir(), "cww-test-task-"));
  }

  test("writes the chosen method's key as the task env (mode 600)", () => {
    const dir = tempTaskDir();
    writeTaskEnv(dir, REPO_URL, { CLAUDE_CODE_OAUTH_TOKEN: "sk-ant-oat01-x" });
    const file = path.join(dir, "env");
    expect(fs.readFileSync(file, "utf8")).toBe("CLAUDE_CODE_OAUTH_TOKEN=sk-ant-oat01-x\n");
    expect(fs.statSync(file).mode & 0o777).toBe(0o600);
  });

  test("removes a stale file when there is nothing to carry", () => {
    const dir = tempTaskDir();
    fs.writeFileSync(path.join(dir, "env"), "CWW_GIT_USER=old\n");
    writeTaskEnv(dir, REPO_URL, {});
    expect(fs.existsSync(path.join(dir, "env"))).toBe(false);
  });
});
