import { describe, expect, test } from "bun:test";
import { buildRefreshContent, collectRefreshEntries, shellQuote } from "../src/lib/env-refresh";

describe("shellQuote", () => {
  test("wraps plain values in single quotes", () => {
    expect(shellQuote("abc123")).toBe("'abc123'");
  });

  test("keeps shell-active characters inert", () => {
    expect(shellQuote("a$b`c")).toBe("'a$b`c'");
    expect(shellQuote("line1\nline2")).toBe("'line1\nline2'");
  });

  test("escapes embedded single quotes", () => {
    expect(shellQuote("it's")).toBe(`'it'\\''s'`);
  });
});

describe("buildRefreshContent", () => {
  test("emits one quoted assignment per entry after the header", () => {
    const content = buildRefreshContent({ A: "1", B: "x y" });
    const lines = content.split("\n");
    expect(lines[0]).toStartWith("# Generated by cww");
    expect(content).toContain("A='1'\n");
    expect(content).toContain("B='x y'\n");
    expect(content).toEndWith("\n");
  });

  test("contains assignments only (no commands), even for hostile values", () => {
    const content = buildRefreshContent({ TOKEN: "x'; rm -rf / #" });
    expect(content).toContain(`TOKEN='x'\\''; rm -rf / #'\n`);
  });
});

describe("collectRefreshEntries", () => {
  const ENV_TEXT = [
    "# agent tokens",
    "CLAUDE_CODE_OAUTH_TOKEN=sk-ant-oat01-abc",
    "MISTRAL_API_KEY='m-key'",
    "CWW_BROWSER=off",
  ].join("\n");

  test("filters the env file down to the given auth keys", () => {
    const entries = collectRefreshEntries(
      ENV_TEXT,
      ["CLAUDE_CODE_OAUTH_TOKEN", "MISTRAL_API_KEY", "ANTHROPIC_API_KEY"],
      null,
    );
    expect(entries).toEqual({
      CLAUDE_CODE_OAUTH_TOKEN: "sk-ant-oat01-abc",
      MISTRAL_API_KEY: "m-key", // quotes stripped by the env parser
    });
  });

  test("never forwards non-auth keys like CWW_BROWSER", () => {
    const entries = collectRefreshEntries(ENV_TEXT, ["CLAUDE_CODE_OAUTH_TOKEN"], null);
    expect(Object.keys(entries)).toEqual(["CLAUDE_CODE_OAUTH_TOKEN"]);
  });

  test("adds the git credential when one matches", () => {
    const entries = collectRefreshEntries("", [], {
      user: "dev",
      token: "pat-123",
      url: "https://forge.example.com/org/repo",
    });
    expect(entries).toEqual({ CWW_GIT_USER: "dev", CWW_GIT_TOKEN: "pat-123" });
  });

  test("empty env file and no credential yields nothing to refresh", () => {
    expect(collectRefreshEntries("", ["CLAUDE_CODE_OAUTH_TOKEN"], null)).toEqual({});
  });
});
